package com.tacoshop.rules

/**
 * DRL rules resource file for our discount rules
 * 
 * @author <a href="mailto:jeremy.ary@gmail.com">jary</a>
 * @since Dec. 2012
 */
 
import main.java.com.tacoshop.model.Purchase

rule "purchase over 15 and less than 25 dollars"
when
	$p : Purchase ( total > 15 && <= 25 ) 
then
	$p.setDiscount(0.10);
	System.out.println("Level 1 discount: " + $p.getDiscount());
end

rule "purchase over 25 dollars"
when
	$p : Purchase ( total > 25 )
then
	$p.setDiscount(0.15);
	System.out.println("Level 2 discount: " + $p.getDiscount());
end

rule "purchase contains combo" salience -1
when
	$p : Purchase ( drinkIncluded, tacoCount >= 2 )
then
	$p.setDiscount($p.getDiscount() + 0.05);
	System.out.println("Combo discount: " + $p.getDiscount());
end
