package com.tacoshop.rules

import main.java.com.tacoshop.model.Alarm
import main.java.com.tacoshop.model.Fire
import main.java.com.tacoshop.model.Sprinkler

rule "fire detected, turn on alarm"
when
	Fire ( $r : room )
	Sprinkler ( room == $r, !on )
then
	System.out.println("fire detected, starting alarm!");
	insertLogical( new Alarm($r) );
end

rule "alarm should turn on sprinklers, extinguishing fire"
when
	Alarm ( $r : room )
	$s : Sprinkler ( room == $r )
then
	System.out.println("alarm sounding, turning on sprinklers");
	modify( $s ){ setOn(true) };
end

rule "sprinkler came on, that puts out the fire"
when
    $f : Fire ( $r : room )
    Sprinkler ( room == $r, on )
then
    System.out.println("sprinklers put out the fire in " + $r);
    retract ( $f );
end
